config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new, :create] do
    member do
      get :following, :followers, :notifications, :join_groups
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show] do
    resources :replies, only: :create, module: "microposts"
  end
  resources :relationships, only: [:create, :destroy]
  resources :groups do
    resources :comments, only: [:create, :destroy]
    member do
      get :members
    end
  end
  resources :group_users, only: [:create, :destroy]
  resources :books do
    resources :reading_progresses, only: [:create, :destroy], module: "books"
  end
  resources :book_users, only: [:create, :destroy]
  resources :reading_progresses, only: :update
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}
  validates :detail, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy, :members]
  before_action :set_group, only: [:show, :destroy, :members, :edit, :update]
  before_action :authorize_group, only: [:index, :new, :create]


  def index
    @groups = Group.all.paginate(page: params[:page])
  end

  def show
    @comment = @group.comments.build
    @comments = @group.comments.includes(:user).paginate(page: params[:page])
  end

  def new
    @group = Group.new
    @user = current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      current_user.join_group_by_admin(@group.id)
      redirect_to group_url(@group)
    else
      render 'new'
    end
  end

  def destroy
    @group.destroy
    flash[:success] = "Group deleted"
    redirect_to groups_url
  end

  def edit
  end

  def update
    if @group.update_attributes(group_params)
      flash[:success] = "group updated"
      redirect_to @group
    else
      render 'edit'
    end
  end

  def members
    @title = "Group members"
    @users = @group.users.paginate(page: params[:page])
  end

  private
  def group_params
    params.require(:group).permit(:name, :detail)
  end

  def set_group
    @group = Group.find(params[:id])
    authorize @group
  end

  def authorize_group
    authorize Group
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_defect.html.erb
<%= form_for(current_user.group_users.find_by(group_id: @group.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Defect", class: "btn" %>
<% end %>

app/views/groups/_group.html.erb
<li>
  <%= link_to "#{group.name}(#{group.group_users.count})", group %>
</li>

app/views/groups/_group_form.html.erb
<%= form_for(@group, url: yield(:action_url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :detail %>
  <%= f.text_field :detail, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/groups/_join.html.erb
<%= form_for(current_user.group_users.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :group_id, @group.id %></div>
  <%= f.submit "Join", class: "btn btn-primary" %>
<% end %>

app/views/groups/_join_form.html.erb
<div id="join_form">
<% if current_user.joining?(@group) %>
  <%= render 'defect' %>
<% else %>
  <%= render 'join' %>
<% end %>
</div>

app/views/groups/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
   | <%= link_to "delete", user, method: :delete, date: {confirm: "You sure?"} %>
  <% end %>
</li>

app/views/groups/edit.html.erb
<% provide(:title, "Edit Group") %>
<% provide(:button_text, "Save changes") %>
<% provide(:action_url, group_path) %>
<h1>Update group information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'group_form' %>
  </div>
</div>

app/views/groups/index.html.erb
<% provide(:title, 'All groups') %>
<h1>All groups</h1>
<h4>
<%= link_to "Make group", new_group_path %>
</h4>

<%= will_paginate @groups %>

<ul class="groups">
  <%= render @groups %>
</ul>

<%= will_paginate @groups %>

app/views/groups/members.html.erb
<h3>Members (<%= @users.count %>)</h3>
<ol class="users">
  <%= render @users %>
</ol>
<%= will_paginate @users %>

app/views/groups/new.html.erb
<% provide(:title, 'Make group') %>
<% provide(:button_text, 'make a group') %>
<% provide(:action_url, groups_path) %>

<h1>Make group</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'group_form' %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="group_info">
      <h1>
        <%= @group.name %>
        <% if current_user.owner?(@group.id) || current_user.admin? %>
         | <%= link_to "delete", @group, method: :delete, date: {confirm: "You sure?"} %><br>
        <% end %>
      </h1>
      <%= @group.detail %>
      <% if @group.users.any? %>
        <%= link_to "#{@group.users.count} join users", members_group_path(@group), class: "members" %>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'join_form' if logged_in? %>
    <h3 id="comment-index">Comments</h3>
    <% if @group.users.include?(current_user) %>
      <section class="comment_form">
        <%= render 'shared/comment_form' %>
      </section>
      <%= render 'shared/comments' %>
    <% else %>
      <p>グループに参加するとメンバーのコメントを閲覧できます。</p>
    <% end %>
  </div>
</div>