config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new, :create] do
    member do
      get :following, :followers, :notifications, :join_groups
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show] do
    resources :replies, only: :create, module: "microposts"
  end
  resources :relationships, only: [:create, :destroy]
  resources :groups do
    resources :comments, only: [:create, :destroy]
    member do
      get :members
    end
  end
  resources :group_users, only: [:create, :destroy]
  resources :books do
    resources :reading_progresses, only: [:create, :destroy], module: "books"
  end
  resources :book_users, only: [:create, :destroy]
  resources :reading_progresses, only: :update
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :mentioned_replies, class_name: "Reply",
              foreign_key: "destination_id"
  has_one :mention_replies, class_name: "Reply",
              foreign_key: "micropost_id"
  # 送られてきたポスト
  has_many :mentioned, through: :mentioned_replies, source: :micropost
  # ポストの宛先
  has_one :mention, through: :mention_replies, source: :destination
  default_scope -> {order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
  validate :picture_size

  before_save :reply_true


  def reply_true
    self.reply = true if is_reply?
  end

  def is_reply?
    if screen_name = content.match(/(?<!\w)@\w+/i)
      pick_user_from_micropost_content(screen_name[0]) ? true : false
    else
      false
    end
  end

  def make_reply(address = nil)
    screen_name = content.match(/(?<!\w)@\w+/i)[0]
    if pick_user_from_micropost_content(screen_name)
      reply = Reply.create do |r|
        r.micropost_id = self.id
        r.destination_id = address if address
      end
      Notification.create do |n|
        n.notifier_id = Micropost.find(address).user_id
        n.notificationable = reply
        n.body = "create"
      end
    end
  end

  def pick_user_from_micropost_content(screen_name)
      screen_name[0] = ""     # @の取り除き
      User.find_by(screen_name: screen_name)
  end

  def collect_go_back_replies
    parent = self.mention
    return [] if parent.nil?
    [parent] + parent.collect_go_back_replies
  end


  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts/replies_controller.rb
class Microposts::RepliesController < ApplicationController

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      if @micropost.reply?
        @micropost.make_reply(@mentioned_id)
        flash[:success] = "reply created!"
        redirect_to micropost_url(@mentioned_id)
      else
        flash[:success] = "Micropost created!"
        redirect_to root_url
      end
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  private

    def micropost_params
      @mentioned_id = params[:micropost_id] || params[:id]
      params.require(:micropost).permit(:content, :picture)
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :set_micropost, only: [:destroy]
  before_action :authorize_micropost, only: [:create]


  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      if @micropost.reply?
        @micropost.make_reply
        flash[:success] = "reply created!"
        redirect_to micropost_url(@micropost)
      else
        flash[:success] = "Micropost created!"
        redirect_to root_url
      end
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_back(fallback_location: root_url)
  end

  def show
    @to_micropost = Micropost.find(params[:id])
    @after_replies = @to_micropost.mentioned
    if @to_micropost.reply?
      @before_replies = @to_micropost.collect_go_back_replies
      # logger.info "MicropostsController#show - before_replies: #{@before_replies}"
    end
    @micropost = Micropost.new
  end


  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture, :destination)
    end

    def set_micropost
      @micropost = Micropost.find(params[:id])
      authorize @micropost
    end

    def authorize_micropost
      authorize Micropost
    end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to "#{micropost.user.name}", micropost.user %> @<%= micropost.user.screen_name %></span>
  <span class="content">
    <% if micropost.reply? %>
      <% screen_name = micropost.content.match(/(?<!\w)@\w+/i)[0] %>
      <% user = micropost.pick_user_from_micropost_content(screen_name) %>
      <%= link_to "@#{screen_name}", user_path(user) %>
      <% micropost.content = micropost.content.sub(/(?<!\w)@\w+/i, "") %>
    <% end %>
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete, date: {confirm: "You sure?"} %>
    <% end %>
  </span>
  <span class="reply">
    <%= link_to "view the details", micropost_path(micropost) %>
  </span>
</li>

app/views/microposts/show.html.erb
<div class="main-post">
  <ol class="microposts">
    <% if @before_replies %>
      <% @before_replies.reverse.each do |rep| %>
        <% content = rep.content.sub(/(?<!\w)@\w+/i, "") %>
        <% length = content.size %>
        <% if length < 15 %>
          <%= link_to "@#{rep.user.screen_name}, #{content}", micropost_path(rep.id) %> >
        <% else %>
          <%= link_to "@#{rep.user.screen_name}, #{content[0, 15]}...", micropost_path(rep.id) %> >
        <% end %>
      <% end %>
      <%= link_to "@#{@to_micropost.user.screen_name}, #{@to_micropost.content.sub(/(?<!\w)@\w+/i, "")}", micropost_path(@to_micropost) %>
    <% end %>
    <div class="replies">
      <%= render @before_replies[0] %>
    </div>
    <%= render @to_micropost %>
      <div class="replies">
        <%= render 'shared/reply_micropost_form' %>
        <%= render @after_replies %>
      </div>
  </ol>
</div>